import Head from "next/head";
import Image from "next/image";
import style from "../styles/Home.module.css";
import Link from "next/link";
import Navbar from "../components/Navbar";
import { AiOutlineMail } from "react-icons/ai";
import { BsFillPlayFill } from "react-icons/bs";
import { FaReact } from "react-icons/fa";

import { HiOutlineDesktopComputer } from "react-icons/hi";

import Projects from "../components/Projects";
import { useEffect } from "react";
import Aos from "aos";
import "aos/dist/aos.css";
export default function Home() {
  useEffect(() => {
    Aos.init({ duration: 2000 });
  }, []);
  return (
    <div className={style.container}>
      <Head>
        <title>RASHEED CODES</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pics.jpg" />
      </Head>
      <Navbar />

      <div className={style.main} id="main">
        <h1>
          Hi, <span style={{ color: " #97DECE" }}>Rasheed</span> here.
        </h1>
        <h3
          data-aos="fade-up"
          data-aos-duration="900"
          style={{ color: "#97DECE" }}
        >
          I CREATE STUFF SOMETIMES.
        </h3>
        <p>SOFTWARE ENGINEER.</p>
        <p style={{ color: "#97DECE" }}>FRONT-END DEVELOPER.</p>
        <p>MOBILE APP DEVELOPER.</p>
        {/* <p data-aos="fade-up" data-aos-duration="1000">
          I'm a software engineer based in Lagos, Nigeria.
          <br /> I have great interest in Data Analytics and Visualization,
          <br />
          artificial intelligence, human-computer interactions,
          <br /> and everything in between.
        </p> */}
        <Link href="mailto:abdulraufrasheed15@gmail.com">
          <button data-aos="fade-up" data-aos-duration="1500">
            {" "}
            <AiOutlineMail size={20} style={{}} /> Say hi !
          </button>
        </Link>
      </div>

      <div id="expertise" className={style.headline} data-aos="fade-right">
        <h1>/. My Expertise /</h1>
        <div className={style.line}></div>
      </div>

      <div
        // className="flex flex-row justify-between flex-wrap rounded-2xl pl-25 pr-25 m-20 divide-x divide-teal-500 border border-teal-300 "
        className={style.topexpertise}
      >
        <div className={style.expertise}>
          <div className={style.menuexpertise}>
            <HiOutlineDesktopComputer size={35} style={{ color: "white" }} />
            <h2 className="text-2xl text-white w-30 ">Software Development</h2>
          </div>
          <div>
            <p className="">
              Experienced in both functional and OOP:Nodejs, Java, JavaScript,
              TypeScript.
            </p>
          </div>
        </div>
        <div className={style.expertise}>
          <div className={style.menuexpertise}>
            <FaReact size={35} style={{ color: "white" }} />
            <h2 className="">
              Frontend Dev React,
              <br /> Next Js
            </h2>
          </div>
          <div>
            <p className="text-white text-xl">
              Passionate about UI/UX. Over 4 years of development experience in
              HTML, CSS, JS, React and NextJS frameworks.
            </p>
          </div>
        </div>
        <div className={style.expertise}>
          <div className={style.menuexpertise}>
            <HiOutlineDesktopComputer size={35} style={{ color: "white" }} />
            <h2 className="">React Navtive Dev Android, IOS</h2>
          </div>
          <div>
            <p className="text-white text-xl">
              Skilled in developing hybrid mobile apps and cross-platform
              solutions using the Flutter framework.
            </p>
          </div>
        </div>
      </div>

      <div id="about" className={style.headline}>
        <h1>/ About</h1>
        <div className={style.line}></div>
      </div>

      <div className={style.about}>
        <div className={style.course}>
          <p>
            A Computer Science major at &nbsp;
            <span
              style={{ color: " #97DECE", cursor: "pointer" }}
              onClick={() => (window.location = "https://aptech-nigeria.com/")}
            >
              Aptech Institution
            </span>
            &nbsp; with two years experience in software engineering and
            currently a Software Development Engineer at{" "}
            <span
              style={{ color: " #97DECE", cursor: "pointer" }}
              onClick={() => (window.location = "https://tm30.net/")}
            >
              TM30-GLOBAL.
            </span>{" "}
            My ambitious interest in software development combined with my drive
            to work for a company that want to move the next level will be a
            unique and enriching experience for both parties. With demonstrated
            history of working in the information industry, I have a user
            experience in frontend development, I am eager to work with an
            organization where professionalism is value while gaining knowlegde
            and experience to advance my career and become an expert in my
            industry.
          </p>

          <p>Here are some technologies i have been working with:</p>

          <div className={style.grid}>
            <div
              className={style.play}
              data-aos="fade-up"
              data-aos-duration="1000"
            >
              <BsFillPlayFill />
              <p>javascript ES6+</p>
            </div>
            <div
              className={style.play}
              data-aos="fade-up"
              data-aos-duration="1000"
            >
              <BsFillPlayFill />
              <p>React JS</p>
            </div>

            <div
              className={style.play}
              data-aos="fade-up"
              data-aos-duration="1000"
            >
              <BsFillPlayFill />
              <p>Next JS</p>
            </div>

            <div
              className={style.play}
              data-aos="fade-up"
              data-aos-duration="1000"
            >
              <BsFillPlayFill />
              <p>Node JS</p>
            </div>
            <div
              className={style.play}
              data-aos="fade-up"
              data-aos-duration="1000"
            >
              <BsFillPlayFill />
              <p>Express JS</p>
            </div>

            <div
              className={style.play}
              data-aos="fade-up"
              data-aos-duration="1000"
            >
              <BsFillPlayFill />
              <p>Postgress </p>
            </div>
          </div>
        </div>

        <img priority src="/mypic.jpg" width={300} height={400} />
      </div>

      <div id="experience" className={style.headline} data-aos="fade-right">
        <h1>/ Experience</h1>
        <div className={style.line}></div>
      </div>

      <div className={style.experience} data-aos="fade-up">
        <div>
          <h1>
            Software Development Engineer Working{" "}
            <span style={{ color: " #97DECE" }}>REMOTELY /</span>
            <span style={{ color: " #97DECE" }}> ON-SITE</span>
          </h1>
          <br />
          <h3>JUL 2022 - Present</h3>
        </div>
        <div className={style.play}>
          <BsFillPlayFill style={{ color: " #97DECE" }} />
          <p>
            Collaborated with experienced cross-disciplinary developers to
            conceive, design,
            <br />
            and bring innovative products and services to market.
          </p>
        </div>
        <div className={style.play}>
          <BsFillPlayFill style={{ color: " #97DECE" }} />
          <p>
            Design and build innovative technologies in a large distributed
            computing
            <br /> environment and help lead fundamental changes in the
            industry..
          </p>
        </div>
        <div className={style.play}>
          <BsFillPlayFill style={{ color: " #97DECE" }} />
          <p>
            Build distributed storage, index, and query systems that are
            scalable, fault-
            <br />
            tolerant, low cost, and easy to manage/use..
          </p>
        </div>
      </div>
      <Projects />
    </div>
  );
}
